org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

# Minecraft / Forge
mc_version=1.20.1
forge_version=47.2.0
mod_version=0.1.0
mod_id=hexblades
mod_group_id=alexthw.hexblades

# Mappings
parchment_mc_version=1.20.1
parchment_version=2023.06.26

# Dependencies
geckolib_version=4.4.4
curios_version=5.7.0+1.20.1
jei_mc_version=1.20.1
jei_version=15.3.0.4
