modLoader="javafml"
loaderVersion="[47,)"
license="BSD License"

[[mods]]
modId="hexblades"
version="${mod_version}"
displayName="Hexblades"
logoFile="hexblades_logo.png"
credits="Alexthw, elucent, bluelotuscoding"
authors="Alexthw, bluelotuscoding"
description='''
A 1.20.1 port of Hexblades for Eidolon, fully brought into the modern platform after completion testing. Weapon behavior may still require additional in-world testing.
'''

[[dependencies.hexblades]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.hexblades]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.hexblades]]
modId="geckolib"
mandatory=true
versionRange="[4.4,)"
ordering="NONE"
side="BOTH"

[[dependencies.hexblades]]
modId="curios"
mandatory=true
versionRange="[5.7,)"
ordering="NONE"
side="BOTH"

[[dependencies.hexblades]]
modId="eidolon"
mandatory=true
versionRange="[0.3,)"
ordering="AFTER"
side="BOTH"

[[dependencies.hexblades]]
modId="botania"
mandatory=false
versionRange="[1.20.1-440,)"
ordering="AFTER"
side="BOTH"

[[dependencies.hexblades]]
modId="ars_nouveau"
mandatory=false
versionRange="[4.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.hexblades]]
modId="malum"
mandatory=false
versionRange="[1.20.1-,)"
ordering="AFTER"
side="BOTH"
